set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L
set guitablabel=%M\ %t


if has("win32") || has("win64")
    let g:is_win = 1
else
    let g:is_win = 0
endif

set guifont=SauceCodePro\ Nerd\ Font\ 16

