source ~/.zpath
# Homebrew
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

# Node
eval "$(nodenv init -)"

# Ruby
eval "$(rbenv init -)"

# Python
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# Enable pyenv-virtualenv auto-activation
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# Go
export GOPATH="$HOME/go"
export PATH=$PATH:$GOPATH/bin

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Java
export JAVA_HOME="`/usr/libexec/java_home -v 1.8`"
