#!/usr/bin/env zsh
# vim: foldmethod=marker foldenable:
function setup_env() {
	
    # True color
    export COLORTERM=truecolor

    export TERM="xterm-256color"
    export LESS="-R -f -F -X -i -P ?f%f:(stdin). ?lb%lb?L/%L.. [?eEOF:?pb%pb\%..]"
    export LESSCHARSET="utf-8"
    # Pager
    export PAGER="${commands[less]:-$PAGER}"

    # Word split
    export WORDCHARS=''

    # Custom zsh completions path
    export fpath=($fpath ~/.zsh_completions)

    # LS COLORS
    # https://github.com/ogham/exa/blob/adfee28fb9bb6f491c822ba4506fafef03909945/Vagrantfile#L163
    export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"



    # LANGUAGE must be set by en_US
    export LANGUAGE="en_US.UTF-8"

    # Editor
    # For Terminal
    export EDITOR="${commands[vim]:-$EDITOR}"
    export EDITOR="${commands[nvim]:-$EDITOR}"
    export CVSEDITOR="${EDITOR}"
    export GIT_EDITOR="${EDITOR}"
    # For GUI
    export VISUAL="${EDITOR}"

    # Less
    export LESS="-R -f -F -X -i -P ?f%f:(stdin). ?lb%lb?L/%L.. [?eEOF:?pb%pb\%..]"
    export LESSCHARSET="utf-8"
    # Pager
    export PAGER="${commands[less]:-$PAGER}"

    # Word split
    export WORDCHARS=''

    # Custom zsh completions path
    export fpath=($fpath ~/.zsh_completions)
}

setup_history() {
    export HISTFILE="$HOME/.zsh_history" # History file
    export HISTSIZE=100000               # History size in memory
    export SAVEHIST=1000000              # The number of histsize
    export LISTMAX=50                    # The size of asking history
    setopt EXTENDED_HISTORY              # Write the history file in the ":start:elapsed;command" format.
    setopt INC_APPEND_HISTORY            # Write to the history file immediately, not when the shell exits.
    # setopt SHARE_HISTORY               # Share history between all sessions.
    setopt HIST_IGNORE_SPACE             # Do not record an entry starting with a space.
    setopt HIST_REDUCE_BLANKS            # Remove superfluous blanks before recording entry.
    setopt HIST_VERIFY                   # Do not execute immediately upon history expansion.
    setopt HIST_BEEP                     # Beep when accessing nonexistent history.
    # Do not add in root
    [[ "$UID" == 0 ]] && unset HISTFILE && SAVEHIST=0
}
setup_env; unset -f setup_env
setup_history; unset -f setup_history
